format = """
[\ue0b6](#86b9c2)\
$os\
$username\
[](bg:#31748f fg:#86b9c2)\
$directory\
[](fg:#31748f bg:#26233a)\
$git_branch\
$git_status\
[](fg:#26233a bg:#1f1d2e)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#1f1d2e bg:#191724)\
$docker_context\
[](fg:#191724 bg:#eb6f92)\
$time\
[ ](fg:#eb6f92)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#26233a bg:#86b9c2"
style_root = "fg:#eb6f92 bg:#86b9c2"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#86b9c2"
disabled = true # Disabled by default

[directory]
style = "bg:#31748f"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#1f1d2e"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#191724"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#1f1d2e"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#1f1d2e"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#26233a"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#26233a"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#1f1d2e"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#1f1d2e"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#1f1d2e"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#1f1d2e"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#1f1d2e"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#1f1d2e"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#1f1d2e"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#1f1d2e"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#1f1d2e"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#26233a bg:#eb6f92"
format = '[ $time ]($style)'
